defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_libero
  - env: libero
  - state_prior: mingpt_libero_best
  - env_vars: env_vars

lazy_init_models: False

# Dataset details
train_fraction: 0.95
batch_size: 64
num_workers: 16
window_size: 10

# Supervision parameters
student_type: latent_entropy_based # latent_entropy_based, unsupervised, IterativeRandom, QueryCapLimit, Random
query_freq: 3
num_queries: 1 # number of queries per access to oracle
randomst_query_percent: 0.2
query_percentage_budget: 1

# Training details
num_training_epochs: 1
data_parallel: False
device: cuda
optim: Adam

lr: 1e-4
weight_decay: 0.1
betas:
  - 0.9
  - 0.95
grad_norm_clip: 1.0
seed: 42

# Prior training details
num_prior_epochs: 100
num_policy_only_epochs: 100
eval_prior_every: 1
save_prior_every: 1

# Logging frequency
eval_every: 1
save_every: 1

# Wandb config
project: libero_experiments
experiment: libero_train

hydra:
  job:
    override_dirname: ${experiment}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
